### ISSUE TITLE
feat: Let the user provide a custom onScroll handler

### ISSUE THREAD

**Issue by ythomop** [codeherence/react-native-header#21]
## Feature Request

There are times when the scroll position is needed, e.g. to hide/show a floating tab bar.

## Proposed Solution

This can be done exactly like the other scroll related handlers are overriden. The user provided onScroll can run after this library's onScroll

**Comment by e-younan** [comment]
Thanks for the enhancement request - I'll look into this tomorrow.

**Comment by e-younan** [comment]
#22
