### ISSUE TITLE
feat: suppress the callback function onScroll

### ISSUE THREAD

**Issue by zvitek** [codeherence/react-native-header#30]
Hi, thanks for a great component that works on the first try and saved me a lot of work.

On the SectionListWithHeaders component you suppress the callback function onScroll.

So it is not possible to detect if the user has reached the end of the content to load the next one.

Do you have a workaround for this or is this rather unthought out functionality?

Thank you!

**Comment by e-younan** [comment]
Hi @zvitek, thanks for the issue.

Have you tried to use the following props for your feature:

- [onEndReached](https://reactnative.dev/docs/virtualizedlist#onendreached)
- [onEndReachedThreshold](https://reactnative.dev/docs/virtualizedlist#onendreachedthreshold)

**Comment by zvitek** [comment]
Oh, my God. Sorry, I didn't realize that the following props are available on the VirtualizedList component.
I modified the implementation and it works perfectly.

Thank you for your amazing work!

**Comment by e-younan** [comment]
@zvitek Thank you! 

As a side note, if you need a custom scroll listener in the future, you can implement one via [onScrollWorklet](https://react-native-header.codeherence.com/docs/components/scroll-view-with-headers#onscrollworklet).
