### ISSUE TITLE
Search bar and filters area

### ISSUE THREAD

**Issue by marijang** [codeherence/react-native-header#32]
Do you plan to implement header search and header filters? Just like react navigation?

**Comment by e-younan** [comment]
You can add your own custom components to the headers in this library. In this case, you would want to add a `TextInput` to the [LargeHeaderComponent](https://react-native-header.codeherence.com/docs/components/scroll-view-with-headers#largeheadercomponent) or [LargeHeaderSubtitleComponent](https://react-native-header.codeherence.com/docs/components/scroll-view-with-headers#largeheadersubtitlecomponent) to implement search.

**Comment by marijang** [comment]
Cool:D

You have only fade in header when large title comes to top? How to achieve like react navigation that title slide ?

**Comment by e-younan** [comment]
Do you mind providing a video displaying what you are referencing?

**Comment by marijang** [comment]
ok like if you have githum mobile app so you can see example on all pages.
Also i have situation that in left header i have Back icon and content like avatar and user name.

so actualy i want to see only back icon but when i scroll large title i want avatar and user name show in header. I don7t want to put into center...

HOw to achive that?
![IMG_6088](https://github.com/codeherence/react-native-header/assets/1381443/339579ee-1ce2-440b-afc6-8cdbdd64b603)

**Comment by marijang** [comment]
ad github example...
![IMG_6090](https://github.com/codeherence/react-native-header/assets/1381443/6645b90f-40e2-4b20-ac39-89d39f4adcb4)

**Comment by e-younan** [comment]
For the back icon + avatar and username, you can do the following in your Header component:

```tsx
import {
  FadingView,
  Header,
  ScrollHeaderProps,
} from '@codeherence/react-native-header';

const HeaderComponent = ({ showNavBar }: ScrollHeaderProps) => {
  const { styles } = useStyles(stylesheet);

  return (
    <Header
      showNavBar={showNavBar}
      headerLeft={
        <>
          <BackButton />
          { /* The "FadingView" is exported from the library as a convenience component. */ }
          <FadingView style={{ flexDirection: 'row', gap: 6 }}  opacity={showNavBar}>
            <Image
              source={{ uri: instrument.logo_url }}
              style={styles.headerLogo}
              contentFit="contain"
              contentPosition="center"
            />
            <Body numberOfLines={1}>username</Body>
          </FadingView>
        </>
      }
    />
  );
};
```

Obviously, adjust the code above to work with your implementation.

For the initial animation you asked about, I am still confused on what exactly you are referencing. Are you talking about when the user presses the back button, the header will animate its contents?

**Comment by marijang** [comment]
Works like a charm:D

How to expand space for left content?

**Comment by marijang** [comment]
![Simulator Screenshot - iPhone 15 - 2024-04-26 at 20 26 56](https://github.com/codeherence/react-native-header/assets/1381443/1bea85ba-cde6-42b2-b20b-5eb00501c61e)

Title is cutted

**Comment by marijang** [comment]
also how to change background color? By the way code is great!:D

**Comment by e-younan** [comment]
> ![Simulator Screenshot - iPhone 15 - 2024-04-26 at 20 26 56](https://github.com/codeherence/react-native-header/assets/1381443/1bea85ba-cde6-42b2-b20b-5eb00501c61e)
> 
> 
> 
> Title is cutted

There is default styling to make the headerLeft and headerRight components have a flex of 1. You need to adjust their styles (i.e., headerStyleLeft and headerStyleRight) accordingly if you want the left side to take up more room.

**Comment by e-younan** [comment]
> also how to change background color? By the way code is great!:D

You can adjust the style of the header via headerStyle. If you want to animate the background colour when the user scrolls, you can use the [SurfaceComponent](https://react-native-header.codeherence.com/docs/components/header#surfacecomponent) prop for more complex interactions.

**Comment by e-younan** [comment]
> ad github example...
> 
> ![IMG_6090](https://github.com/codeherence/react-native-header/assets/1381443/6645b90f-40e2-4b20-ac39-89d39f4adcb4)
> 
> 

This animation is not supported at the moment. You could easily implement this by using the scrollY that is provided to the HeaderComponent and LargeHeaderComponent - it's just a simple translation.

**Comment by marijang** [comment]
Yep it will be cool to be in packgage it will be great:D
That will be new feature:D

**Comment by marijang** [comment]
also my suggestion is to add search maybe filters and buttons in package:D

**Comment by e-younan** [comment]
> Yep it will be cool to be in packgage it will be great:D That will be new feature:D

Feel free to open a PR introducing this feature! I will close this issue for now, if you are having any issues in the future, feel free to open another one. :)
