### ISSUE TITLE
feat: publish example on expo

### ISSUE THREAD

**Issue by MBach** [codeherence/react-native-header#33]
## Feature Request

Great package!

I'm starting to play with it, reading the docs, etc. I think the "dev user experience" could be improved by providing a link to expo to quickly see how it's going.

**Comment by e-younan** [comment]
Thanks for opening up this issue!

By a link to expo, do you mean an Expo Snack of the `example` application? If so, I think that since the example application is ejected, it may not be feasible (from what I remember, only Expo Go applications worked in Expo Snacks).

**Comment by MBach** [comment]
Ah OK, that's unfortunate. Expo Snack is quite good to play around.

**Comment by MBach** [comment]
https://snack.expo.dev/@bachelier/react-native-header-example?platform=android

**Comment by e-younan** [comment]
Oh, I guess I was wrong! Thanks for creating this - I will add a Snack now. :)

**Comment by e-younan** [comment]
Thanks for the suggestion @MBach! This has been merged and released as a new version (0.12.2). You should be able to see the new QR code and link on [npm](https://www.npmjs.com/package/@codeherence/react-native-header).
