### ISSUE TITLE
useScrollViewOffset hook is only in react-native-reanimated >= 2.11.0 available

### ISSUE THREAD

**Issue by matjua17** [codeherence/react-native-header#4]
## Description

The `useScrollViewOffset` hook is only available in react-native-reanimated >= 2.11.0. 

## Expected behavior

Should work with all react-native-reanimated 2 versions.

## Actual behavior

Error occurs: Undefined is not a function. Due to the availability of useScrollViewOffset only in >= 2.11.0 version of reanimated. 

## Environment

|||
| --------------------------------- | ---------------------------------- |
| react-native-header | v0.6.0 |
| Platform & OS (if applicable) | iOS/Android/Web |
| react-native-reanimated | < v2.11.0 |
| react-native-safe-area-context | v4.5.0

**Comment by e-younan** [comment]
Thanks for opening this issue up. Exploring solution here: [#3](https://github.com/codeherence/react-native-header/pull/3)

**Comment by e-younan** [comment]
I just released a fix for this. See [0.7.0-rc.0](https://github.com/codeherence/react-native-header/releases/tag/v0.7.0-rc.0) or install it with: 

```
yarn add @codeherence/react-native-header@0.7.0-rc.0
```

**Comment by e-younan** [comment]
#3
