### ISSUE TITLE
bug: Header visibility not working with FlashList

### ISSUE THREAD

**Issue by stanete** [codeherence/react-native-header#40]
## Description

The HeaderComponent visibility is not working when using FlashListWithHeaders component, while it works correctly with regular FlatList and ScrollView. The issue appears to be related to how FlashList handles animated scroll events with react-native-reanimated.

## Reproduction

1. Create a screen using FlashListWithHeaders:

```tsx
import { FlashListWithHeaders, Header, LargeHeader } from '@codeherence/react-native-header';
import React from 'react';
import { Text, View } from 'react-native';

// Simple HeaderComponent using Header from the library
const HeaderComponent = ({ showNavBar }) => (
  <Header
    showNavBar={showNavBar}
    borderColor="#e5e5e5"
    initialBorderColor="white"
    headerStyle={{
      backgroundColor: 'white',
    }}
    headerCenter={
      <Text style={{ padding: 12, fontSize: 16, fontWeight: '600' }}>
        Simple Header
      </Text>
    }
  />
);

// Simple LargeHeaderComponent using LargeHeader from the library
const LargeHeaderComponent = () => (
  <LargeHeader
    headerStyle={{
      backgroundColor: 'white',
      paddingVertical: 0,
      paddingHorizontal: 0,
    }}
  >
    <View style={{ padding: 16 }}>
      <Text style={{ fontSize: 24, fontWeight: '600' }}>Large Header</Text>
      <Text style={{ fontSize: 16, color: '#666' }}>Subtitle text</Text>
    </View>
  </LargeHeader>
);

// Mock data
const data = Array.from({ length: 50 }, (_, index) => ({
  id: `item-${index}`,
  title: `Item ${index}`,
}));

export default function Screen() {
  return (
    <FlashListWithHeaders
      HeaderComponent={HeaderComponent}
      LargeHeaderComponent={LargeHeaderComponent}
      data={data}
      renderItem={({ item }) => (
        <View style={{ padding: 16, borderBottomWidth: 1, borderBottomColor: '#e5e5e5' }}>
          <Text>{item.title}</Text>
        </View>
      )}
      estimatedItemSize={50}
      headerFadeInThreshold={0.5}
    />
  );
}

```
2. Scroll the list
3. The header should appear when scrolling down, but it remains invisible

## Expected behavior

The HeaderComponent should fade in when scrolling down and the LargeHeaderComponent should fade out, similar to how it works with regular FlatList and ScrollView.

## Actual behavior

- No scroll events are being detected from the FlashList component
- The HeaderComponent remains invisible regardless of scroll position
- The same implementation works correctly with FlatList and ScrollView

## Environment

| Package | Version |
| --------------------------------- | ---------------------------------- |
| react-native-header | ^0.14.0 |
| Platform & OS | iOS/Android |
| react-native-reanimated | ~3.10.1 |
| react-native-safe-area-context | 4.10.5 |
| @shopify/flash-list | 1.6.4 |
| react-native | 0.74.5 |
| expo | ~51.0.39 |

## Additional Information 

I found (in reality Claude did) a workaround In useScrollContainerLogic.ts file that may give you some hint on what's the issue.

Original Implementation (not working with FlashList):

```tsx
const scrollHandler = useAnimatedScrollHandler((event) => {
  'worklet';
  if (onScrollWorklet) onScrollWorklet(event);
  scrollY.value = event.contentOffset.y;
});
```

Workaround (working with FlashList):

```tsx
const handleScroll = (event: NativeScrollEvent) => {
  scrollY.value = event.contentOffset.y;
};

const scrollHandler = useCallback((event) => {
  'worklet';
  runOnJS(handleScroll)(event.nativeEvent);
}, []);
```

**Comment by e-younan** [comment]
Hey there, thanks for opening the issue! I have been using the library in a project that I am working on extensively and the `FlashListWithHeaders` component works fine in terms of visibility. I'll create a repo with the versions of the libraries you cited and test it.

As far as the workaround you cited:

```tsx
const handleScroll = (event: NativeScrollEvent) => {
  scrollY.value = event.contentOffset.y;
};

const scrollHandler = useCallback((event) => {
  'worklet';
  runOnJS(handleScroll)(event.nativeEvent);
}, []);
```

You shouldn't be using `runOnJS` to handle scroll events. Offloading this to the UI thread will improve performance.

**Comment by e-younan** [comment]
I was able to repro the issue with the reanimated version you cited. However, after updating to the latest version of react-native-reanimated, everything works as expected. Here is a repository with your code:

https://github.com/e-younan/test-rnh-issue40

It's kind of hard to keep track of which versions of reanimated are not working with the library - I'll review them and update the docs to make sure there is a note about this.

**Comment by stanete** [comment]
Indeed updating reanimated, everything works as expected. However, I can see this warning logged:

```sh
LOG  LargeHeader props: {"scrollY": {"_isReanimatedSharedValue": true, "addListener": [Function addListener], "modify": [Function modify], "removeListener": [Function removeListener], "value": 0}, "showNavBar": {"_isReanimatedSharedValue": true, "addListener": [Function addListener], "modify": [Function modify], "removeListener": [Function removeListener], "value": 0}}

WARN  [Reanimated] Reading from `value` during component render. Please ensure that you do not access the `value` property or use `get` method of a shared value while React is rendering a component.

If you don't want to see this message, you can disable the `strict` mode. Refer to:
https://docs.swmansion.com/react-native-reanimated/docs/debugging/logger-configuration for more details.
```

**Comment by e-younan** [comment]
Use the latest (3.16.3). Did you check out the example repo?
