### ISSUE TITLE
Does react-native-header work with react-native-tab-view?

### ISSUE THREAD

**Issue by timothygorer** [codeherence/react-native-header#8]
I was curious if react-native-header works with react-native-tab-view with lazy mode enabled. I tried building my own header from scratch using reanimated before I discovered this library, and I ran into a bug with react-native-tab-view lazy={true} where if I scrolled down the FlatList in one tab and then went to another tab, the header would disappear and the FlatList would be offset in the Y direction. The header would reappear and the FlatList offset would correct itself once the user started scrolling vertically again. Perhaps it's a problem with my implementation, but I was wondering if someone could do an experiment with react-native-header + react-native-tab-view to see if the same thing occurs. The problem doesn't occur when lazy={false}.

**Comment by e-younan** [comment]
I [created a Snack](https://snack.expo.dev/@eyounan/rng-with-tabs) to try to replicate your issue - but I am not seeing any issues. Can you check out the Snack and see if you observe the problem?

**Comment by timothygorer** [comment]
Thanks for doing that. I have a unique implementation where the tabs are floating on the bottom of the screen rather than the top. I'll take a look later today.

**Comment by e-younan** [comment]
Closing. Feel free to re-open if there are any issues.
